### PR TITLE
Add code of conduct to page

### PR DESCRIPTION
**Pull request by dcwalk**
Just waiting for final thoughts/comments on our Code of Conduct and guidelines on https://github.com/tomeshnet/documents/pull/23 before merging this in

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey, @garrying or @slowmanchan this is ready to go. 

Can I get a review? (not trusting myself right now, too much on the go)

**Comment by benhylau** [comment]
lgtm thanks @dcwalk glad the CoC is finally getting formalized 👍

**Comment by garrying** [comment]
Looks good to me as well 👍 . Small thought on formatting: Should all written instances of _Code of Conduct_ be in title case?

**Comment by dcwalk** [comment]
Agree @garrying , I've updated!

**Comment by dcwalk** [comment]
@garrying can you let me know what should be done RE: travis above? (failed check). What should the process be, merge anyway?

It looks like it is form a link check. Nothing to do with this PR.

(Edit: I rebased on master as I think it might have to do with the fact that the travis config was merged in after..?)

**Comment by garrying** [comment]
@dcwalk The reason it failed is probably what you mentioned. Merges can still happen on failures, though it'd be good to check the jenkins build page to make sure it's not failing on `jekyll build`.

**Pull request merged**
