### PR TITLE
Home page Rework [WIP]

### PR DESCRIPTION
**Pull request by darkdrgn2k**
New home page with a horizontal 3 image look.

TODO
- [ ] Create images for 3 item @Shrinks99 
- [x] Dependent on build-a-node page being added PR #171  (reason for Travis failure)

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey, I thought @Shrinks99 was working through a new homepage layout, and I'm probably out of date, but didn't think it was heading in this direction!

**Comment by darkdrgn2k** [comment]
This is @Shrinks99 project i just commited the changes he wanted to make.

**Comment by dcwalk** [comment]
Okay circling back on this, and clearing up my confusions:

- It would be good to have the images in order with the menu items
- I think we might want to increase the size of the images?
- Wondering if we want a 1/2 sentence blurb under image to set it up
- Feeling like the hero could be a place to get people checking out the map...? (then have "About" "Get Involved" and "Build a Node" at the three columns?
- Shit we gotta get some events up ;)
- Thinking we could handle distinguishing the footer by use of colour position against the the Event section? (related #179)
- Not feeling the lavendar, but thinking we might want to tone down that primary blue with so many buttons 😂

**Comment by dcwalk** [comment]
Hey, just checking in on this. @Shrinks99 are you feeling keen on the graphic design plan you had planned out in the fall?

**Comment by Shrinks99** [comment]
I'm moving forward on it (very slowly and working infrequently) and
thinking about a full site restructure however nothing has progressed
outside of my sketchbook at the moment.

**Comment by Shrinks99** [comment]
Should probably close / do something with this.  Thinking about the beginnings of a total redesign in the future anyways after we have some sort of more production ready device.

**Pull request closed without merging**
