### PR TITLE
License website content

### PR DESCRIPTION
**Pull request by dcwalk**
This will address Issue #14, so far:
- [x] add CC-BY-SA 4.0 license to the `README.md`
- [x] ~~add CC license to repo in `LICENSE.md`~~
- [X] add GPL license to repo in `LICENSE.md`
- [X] add license(s) to website
- [X] fit in GPL license for code

### CODE REVIEW

**Comment by dcwalk** [comment]
@benhylau or @garrying ... thoughts on how to have both licenses on the website/repo?

**Comment by garrying** [comment]
Would it make sense for GPL to go into `LICENSE` and note it with the CC-BY-SA in `README`? Something like:

> Code released under the GNU General Public License v3.0. tomesh.net website content and documentation released under Creative Commons Attribution-ShareAlike 4.0 International License.

**Comment by dcwalk** [comment]
That makes perfect sense! Thanks, will switch and ping when ready for review

**Comment by dcwalk** [comment]
Okay. I've added to readme...

Two questions:
1. I think we (all people who have contributed to the repo) have to comment on here saying we are okay switching to the GPL
2. Are we allowed to 'assign' copyright to an informal org (Toronto Mesh) or should we say Toronto Mesh Contributors? I believe we have to do the latter.

Also, should we update our contributor guidelines making it clear that we are using CC and GPL?

**Comment by benhylau** [comment]
But that was 3 questions...
1. Yes I am okay with GPL as I mentioned in #14 and [@dcwalk, @garrying, @benhylau] makes up "all people who have contributed to the repo".
2. I believe each contributor can be copyright holder of their respective contribution.
3. Yes.

**Comment by dcwalk** [comment]
True @benhylau !

Also, for the record: as a contributor, I approve switching the license for the Toronto Mesh to GPL 3.0.

Footer note added. @garrying I'm afraid to style anything. Can you make things better? Thanks

**Comment by ansuz** [comment]
I haven't contributed anything but I'm :+1: for GPL.

**Comment by garrying** [comment]
@dcwalk committed a layout edit and an edit to the cc text.

**Comment by dcwalk** [comment]
@garrying much better!

I think if you just explicitly state you are okay switching to GPL we are good to go!

**Comment by benhylau** [comment]
@garrying Comment and merge to close this off?

**Pull request merged**
