### PR TITLE
Update vision statement

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Comment by benhylau** [comment]
Vote (dcwalk edit: on original version)

**Comment by dcwalk** [comment]
@benhylau I think moving stuff to the top makes sense. I have a bit of a cadence issue with the 'sold' portion of the first sentence.

Could we make the first line a little closer to what it was before? 
e.g. _Internet service is currently a black-box to most of its users_
And maybe adjust the second so we don't repeat users then:
e.g. _We are building a community-owned infrastructure that gives us:_

so all told: 

> Internet service is currently a black-box to most of its users. We are building a community-owned infrastructure that gives us:   
> - **agency** to make important decisions about their privacy
> - **autonomy** to access information in an uncontrolled/free manner
> - opportunity to develop **technical literacies**
> - a **resilient** and redundant network
> - open, lower-cost **access** to the World Wide Web

**Comment by garrying** [comment]
+1 to @dcwalk's edit

**Comment by dcwalk** [comment]
@benhylau @garrying looks good! Do we need to re-vote? Maybe on the top comment?

**Comment by vcifani** [comment]
first one might need to be changed to "...about privacy" for grammar... or maybe changed to "privacy decisions" ?
thumbs up!

**Comment by dcwalk** [comment]
@vcifani yeah, good catch!

**Comment by dcwalk** [comment]
Based on our meeting today, we are currently sitting with this vision statement:

> The internet is currently not open and inclusive for all people. We are building a community-owned infrastructure that gives us:
> - open, lower-cost **access** to the World Wide Web
> - a **resilient** and redundant network
> - **agency** to make important decisions about privacy
> - **autonomy** to access information in a free manner
> - an opportunity to develop **technical literacies**

**Comment by structur** [comment]
What does open mean below? What does inclusive mean? Does it mean 'affordable'? Does it mean they don't have representative communities? Does it mean they have trouble interfacing with internet objects as they are designed? 

"The internet is currently not open and inclusive for all people."

**Comment by benhylau** [comment]
@structur It's an ambiguous term which the points following should serve to qualify. I think it's all the things you have pointed out, and although I see some of our currents points as what derives from an _open protocol run on commodity hardware_, that link may not be obvious.

We should perhaps remove the word _open_ in the first point. Proposing: `open, lower-cost access to the World Wide Web` -> `right to low-cost and equal access to the World Wide Web`

**Comment by dcwalk** [comment]
Per conversation regarding #37 , we are going to go ahead with the most recently discussed version of the vision statement.

**Pull request merged**
