### PR TITLE
Create ICS and button to download from main page

### PR DESCRIPTION
**Pull request by dcwalk**
This would address #9 (finally!), moved @garrying 's work from PR #13.

### CODE REVIEW

**Comment by dcwalk** [comment]
@garrying, @daynaclowe (hi!) or @benhylau...
can you test this?

It is passing using a [validator](http://icalendar.org/validator.html), but I'm having trouble loading it using my calendaring app.

Part of the issue was with the timezone before, for reference, here is a calendar in the same timezone (America/Toronto): [uwaterloo](https://uwaterloo.ca/orientation/events/calendar.ics)

**Comment by garrying** [comment]
I was able to import events to Google Calendar, Thunderbird, and Calendar.app from the `.ics`.

**Comment by dcwalk** [comment]
Thanks @garrying it worked today when I tested as well... maybe was dlding a cached copy.

Anyway, I've also added back the button, hopefully nicer placement and language! Ready to be reviewed for merge.

**Comment by benhylau** [comment]
Smart way to do this :)

**Comment by dcwalk** [comment]
@benhylau, it is all @garrying!

**Pull request merged**
