### PR TITLE
Make menu fixed at the top of the page

### PR DESCRIPTION
**Pull request by darkdrgn2k**
Make the nav bar across the top stick to the top of the page when scrolled.

Thoughts?

### CODE REVIEW

**Comment by dcwalk** [comment]
On pages that aren't the home page the heard (e.g. "About" and "Events") is hidden by the menu.

This can be resolved by adjusting content div or head section css

**Comment by darkdrgn2k** [comment]
Issue Corrected but padding the post div

**Comment by garrying** [comment]
Closing or #165

**Comment by darkdrgn2k** [comment]
There is some code in this PR that is specific to the map currently in DEV but not in MASTER.

Once the MASTER PR is commited, and DEV is synced the Map code will be all that's left in this PR

**Comment by darkdrgn2k** [comment]
Well all the other prs are now closed, i guess this one should be to, sorry for reopening it.

**Comment by dcwalk** [comment]
No worries! The code for `#map` is relatively small, so we can just commit to the dev branch directly!

**Pull request closed without merging**
