### PR TITLE
Switch front image to stamen design map

### PR DESCRIPTION
**Pull request by dcwalk**
This pulls over the change to the front page image from #159.

One question I have is image sizing -- I used @darkdrgn2k's compressed version, but wondering if we want to upstep a bit? 

Edit: Oop, and another -- I followed [stamen's citation reccomends](http://maps.stamen.com/#watercolor/12/37.7706/-122.3782) only partially... so please in particular check that language!

### CODE REVIEW

**Comment by Shrinks99** [comment]
The attribution needs to be changed
`Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY SA</a>.`

I think I changed the brightness of the overlay as well in my old implementation to make the map less dark.  Other than that we're good.

**Comment by darkdrgn2k** [comment]
> but wondering if we want to upstep a bit?

Files Size sits at about 250kb right now 

Initial image was over 4 megs
https://raw.githubusercontent.com/tomeshnet/tomesh.net/4cc19211345821e4d1dcebb6d145cb52705af411/images/mesh.jpg

First attempt at shrinking it i got it down to about 1 meg
https://raw.githubusercontent.com/tomeshnet/tomesh.net/2ac2866a6f3a7e721c24578b2e79104edf38ac1e/images/mesh.jpg

Both of those sizes are WAY to big for a simple hero image.

The image itself is huge size at  2496x1764 
This is about 65% bigger then 1080HD (height wise) and in reality only has a ~ 1905x370 area on the site at 1080 resolution

**Q:** Perhaps look at making it smaller? 
**Q:** Do we have a max-target resolution for the site?

**Comment by dcwalk** [comment]
Maybe we scale the image then? I'm at home now, but on my desktop monitor it seemed like there were noticeable compression artifacts.

**Comment by darkdrgn2k** [comment]
Here are two options resized from the original 

1920 Wide version  at 777kb
https://raw.githubusercontent.com/darkdrgn2k/tomesh.net/45a45460c95281cf30593fc3de503631a1c288e2/images/mesh.jpg

1920 Wide version at 298 KB
https://raw.githubusercontent.com/darkdrgn2k/tomesh.net/414b9e14407c895e590863bc26d4a32f96b693c6/images/mesh.jpg

I still think 777 is a little big so if you want that quality I'd suggest cropping the image down so its wide (how much you can crop depends if you want Parallax or not)

**Comment by darkdrgn2k** [comment]
Also I would suggest anchoring the image to the bottom of the DIV so the waterfront is visible, I think it would just make the map a bit more identifiable as Toronto 

Suggested change in  CSS in .feature 

from 

`background-position: center;`

to

`background-position: bottom;`

**Comment by dcwalk** [comment]
Thanks @garrying! Just starting to resurface 😓

**Pull request merged**
