### PR TITLE
Add historical civic tech meetups as events

### PR DESCRIPTION
**Pull request by dcwalk**
Did this just to get the history on the website, we should generate a template that works going forward, I think it should be fairly simple, but wanted feedback on this. 

Sorry, this was just a quick f&r job, not templated correctly!

### CODE REVIEW

**Comment by benhylau** [comment]
Yea I think meeting notes and perhaps [content here](https://github.com/tomeshnet/documents/blob/master/README.md) should be on website somewhere, either fully rendered or linked to.

Issue with current layout is, it's hard for people to view one after the other, because it's a post and they have to click into a link within that post. Maybe if we do a single page that lists all the meeting notes? Like this: https://nycmesh.net/blog/

One page listing all Events. One page listing all Meeting Notes. Nightly job automatically pulls from **documents** repo. What do you think?

**Comment by dcwalk** [comment]
Yo--- good point about the content. The rest should go up!

We ( @garrying and @YKCzoli ) discussed leaving meeting minutes on github as markdown is rendered nice enough and they are a bit of a deep dive into tomesh. I think we could have an 'About' and 'Contribute' page with those details.

Opening a new issue for that: #26

 I'm gonna abstract a template and for the ctto events in this PR, rest should be covered separately.

**Comment by dcwalk** [comment]
Hey @daynaclowe any thoughts on jekyll best practises for handling like post templates?

I was thinking something like the [YAML front matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults)? But how to handle generating them?

**Comment by dcwalk** [comment]
Hey! So I've updated the events to fix a date rendering issue and switch to a templated form for rendering dates: 

> A recap of what we discussed is available in the [ {{ page.date | date: '%B %d, %Y' }} meeting notes](https://github.com/tomeshnet/documents/blob/master/meeting_notes/{{ page.date | date: "%Y%m%d" }}_meeting-notes.md.

(intentionally broken as apparently I don't know how to escape in github markdown.

I've got a couple changes to push, one unfortunately breaks 2 previous links as it changes the post/date slugs--- @garrying can you give some eyes? I want to change the permalink to 

> permalink: /:year-:month-:day/:slug/
> in **config.yml** because all our ctto meetings have the same name.

**TODO:** best way to handle scripting/creating a batch of these?

**Comment by dcwalk** [comment]
Okay, going on 2 weeks without review I'm gonna roll with what I've got and merge as this is all just historical content. Please let me know if there are any issues, but I've tested and haven't encountered any.

I moved work for 'future' events to PR #32 .

**Pull request merged**
