### PR TITLE
Add install party on September 21

### PR DESCRIPTION
**Pull request by dasanchez**
Monthly install party resumes after August skip

### CODE REVIEW

**Review by benhylau — APPROVED** [review]

**Comment by dcwalk** [comment]
The checks are failing on links out from timeline, we should add the flakey flag to 'em if the want? Probably not required here.

Also, I emailed to clear whether we are good to use the room for this date, but looks great otherwise! Can we wait until I hear back?

**Comment by dasanchez** [comment]
_...we should add the flakey flag to 'em..._
Where can I find an example?

_Can we wait until I hear back?_
Sure thing!

**Comment by dcwalk** [comment]
the tag is `data-proofer-ignore`
https://github.com/tomeshnet/tomesh.net/search?utf8=%E2%9C%93&q=data-proofer-ignore&type=

https://github.com/gjtorikian/html-proofer/

But again, not sure it is necessary, just an option!

**Comment by dcwalk** [comment]
Heard back @dasanchez  and we can use the space for the following dates:
- Thurs, Sept 21 7-9
- Thurs, Oct 26 7-9
- Thurs, Nov 16 7-9
- Thurs, Dec 7 7-9

Why don't we add these all in one PR and get 'em up now?

**Comment by dasanchez** [comment]
@dcwalk thanks a bunch! I'll add another commit as soon as I get home to include these dates.

**Review by dcwalk — APPROVED** [review]

**Pull request merged**
