### PR TITLE
Add travis support for publishing to githubpages

### PR DESCRIPTION
**Pull request by darkdrgn2k**
Part of #267 

Current site: https://tomeshnet.github.io/

### CODE REVIEW

**Comment by benhylau** [comment]
I assume the website will be fixed once we migrate the URL back to tomesh.net

I'd be happy to kill the droplet and move to this, but also mindful that this will not allow us to serve up the page on cjdns / yggdrasil, and maybe host IPFS / Dat versions, etc. Basically it kills https://github.com/tomeshnet/mesh-services/issues/1 though those can be future problems.

**Comment by Shrinks99** [comment]
> This will not allow us to serve up the page on cjdns / yggdrasil, and maybe host IPFS / Dat versions, etc.

I think this should be a problem for a later date.  Having a script that can be set up as a cronjob to `curl` tomesh.net once a day and then host the content on IPFS and DAT could be neat?  That way we could all set up our own distributed mirrors if we wanted though I'm not what the complications are there.  @darkdrgn2k and I discussed this a bit and he seemed to be able to mirror content pretty fast though!

We should rename this repo if we are using GitHub pages!  GitHub pages repos must be named orgname.github.io to work properly (you can see that one has been created with this name) and it will compile the Jekyll site automatically, no need for any deployment overhead nonsense!  The ins and outs of this are all available [here](https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites).

It should also be noted that the workshop mini-website is hosted with GitHub pages already over at https://tomeshnet.github.io/p2p-internet-workshop.  All this means is that the /p2p-internet-workshop/ URL can't be used and it will work just fine as is similairly to how https://wilkinson.graphics/transit-over-time functions once the domain is all set up.

EDIT: This approach will have some problems (as pointed out by @darkdrgn2k) with how we currently rebuild the website each day which may not be as doable with the standard github pages setup.

**Comment by benhylau** [comment]
Nah we can still use tomesh.net, just need to point DNS to github. I do this with https://distributed.press, it's on github pages.

For IPFS and Dat, we can do it in the Travis VM using existing tools (there's a small bug with the IPFS tool but aside from that...) we don't need to run a server to do some weird curl thing. See: https://github.com/ournetworks/ournetworks.ca/blob/master/.travis.yml#L53-L57

If we build on merge to master, there is no need to schedule nightly builds.

So aside from no cjdns / yggdrasil, and if we're okay to "host" ipfs and dat content not on our own servers, we should be good.

**Comment by darkdrgn2k** [comment]
> So aside from no cjdns / yggdrasil, and if we're okay to "host" ipfs and dat content not on our own servers, we should be good.

The only other issue is events.

image

**Pull request merged**
