### PR TITLE
Fix front page image

### PR DESCRIPTION
**Pull request by darkdrgn2k**
Front page image tinting using CSS was broken on IE and maybe other browser making it hard to read the text as its white against a very light images.

Instead of CSS tinting, the map image is tinted and tint removed.

### CODE REVIEW

**Comment by garrying** [comment]
Do you know which version of IE this is happening on? CSS3 alpha color is fairly well supported. If it's IE8, we should be able to add a `filter` property to the background tint class.

**Comment by darkdrgn2k** [comment]
IE 11
index

**Comment by garrying** [comment]
@Shrinks99 do you have a high resolution version of the background? I think we can address this IE bug and compression quality in one go with this PR.

**Comment by Shrinks99** [comment]
mesh

Here's the full resolution image.  IE 11 makes me sad.

**Pull request merged**
