### PR TITLE
Add Theme to map

### PR DESCRIPTION
**Pull request by darkdrgn2k**
Applies @Shrinks99 Theme to the google map

### CODE REVIEW

**Comment by darkdrgn2k** [comment]
I would like to see if we can add buildings to this theme as well (to help ID possible LOS errors)

**Comment by garrying** [comment]
Agreed on building details. @Shrinks99 are there specific issues we are addressing with the default map style? I think this colour scheme is better for emphasizing the nodes, but maybe we can preserve some of the shading/tinting to help with defining features like parks, railways, non-residential areas, etc.

**Comment by darkdrgn2k** [comment]
We were having some issue turning the buildings back on... I'll add a toggle in the future. 

As for theme I'll defer to @shrinks99

**Comment by Shrinks99** [comment]
@garrying The issues we are addressing with the theme revolve around highlighting the information we want to convey with the map.  As far as I'm aware all people need to see on the map is where nearby nodes are and how they connect with each-other.  Railways were turned off because I didn't think they were necessary but other point of interest geometry can be turned on if need be.  Currently I think it should like like this:
screen shot 2018-03-25 at 5 17 15 pm

I think what is currently available is a good balance between detail and reduction of the default amount of information.  Buildings are probably a worthwhile consideration but we were having some trouble getting them all working properly.

**Comment by garrying** [comment]
@Shrinks99 Thanks for the background and considerations. The image you posted looks different from what's in this PR. Are we waiting on an addition change to this PR? Think we left off at trying to get buildings to show.

**Comment by darkdrgn2k** [comment]
We have not been successful to get the buildings to show (bug in google maps?). However I added a toggle to turn the theme on and off to put the buildings back.

**Comment by darkdrgn2k** [comment]
The map does look a little different then the styler. I think it may have to do with inheritance, or maybe a bug in google maps.

But this is what the theme looks like on the site

screenshot from 2018-04-07 19-13-25

**Comment by darkdrgn2k** [comment]
:+1:  or :-1: ?

**Pull request merged**
