### PR TITLE
Refactor icons includes and update footer

### PR DESCRIPTION
**Pull request by dcwalk**
This is a setup PR for a larger one restructuring our website!

### CODE REVIEW

**Comment by benhylau** [comment]
We need to add Matrix as our chat. Possibly delete the link to Slack.

**Comment by dcwalk** [comment]
Hey @benhylau totally agree! As this was just a refactor can we bring the slack park in line with the rest in this PR and add Matrix in the PR #37 one?

**Comment by benhylau** [comment]
So this can be merged?

**Comment by dcwalk** [comment]
Good to merge, I went for it.

**Pull request merged**
