### PR TITLE
Timeline 2018

### PR DESCRIPTION
**Pull request by darkdrgn2k**

### CODE REVIEW

**Comment by darkdrgn2k** [comment]
Few other things we can add if you want. I got some of the text started. You are welcome to change/modify/completely replace etc as you see fit.

Just suggestions based on past templates.

- [x] Our Networks
Missing some details. ~~~Template from last year~~~ Suggested by DCWalk

> Members helped organize the second State of Our Networks, with the theme of "Beyond DIY: Do It With Others" here in Toronto. Toronto Mesh members streamed the conference over IPFS, you can watch the videos at XXX.

- [x] ~~~DWeb~~~ (Added to pr)

>~~~Members went to the [DWeb](https://decentralizedweb.net/) summit in San Francisco. We gave a lightning talk, demonstrated our [meshstream](https://github.com/tomeshnet/meshstream/) prototype and discussed the future of distributed work in Toronto with interested parties.~~~

**Comment by benhylau** [comment]
@dcwalk wanna do the recap for OurNetworks? How do you want to archive / link all the retrospective? Including [the livestream one](https://hackmd.io/SEB5MgPoQWGYTWA4Mk5JRA#Hopes-and-Dreams)?

**Comment by dcwalk** [comment]
I would favour language for Our Networks along these lines:

"Members helped organize the second [State of Our Networks](https://ournetworks.ca/2018), with the theme of "Beyond DIY: Do It With Others" here in Toronto. Toronto Mesh members [streamed the conference over IPFS](), you can watch the videos at [XXX]()"

**Comment by benhylau** [comment]
I think we can merge this and add Our Networks video link later.

**Review by benhylau — APPROVED** [review]

**Pull request merged**
