### PR TITLE
Make events.ics work with Android Calendar

### PR DESCRIPTION
**Pull request by benhylau**

### CODE REVIEW

**Review by garrying — APPROVED** [review]

**Comment by dcwalk** [comment]
I think there was a reason we added those in the first place-- dim memories of trying to validate the ics before (it was a nightmare!!)

Can we sit on this for a day or so while I check around again?

**Comment by benhylau** [comment]
@dcwalk Sure, also check scrollback on #website chat from few days back re: this.

**Comment by garrying** [comment]
@dcwalk Do you recall how we were validating? Would be helpful for #136

**Comment by benhylau** [comment]
I tested with my 5x downloading a manually created file I hosted from my laptop to the LAN. Would be nice to have another person verify, otherwise merge and test?

**Comment by dcwalk** [comment]
Hey, sorry for the delay.

I dug up the original thing which led to the inclusion...
https://icalendar.org/iCalendar-RFC-5545/3-2-19-time-zone-identifier.html
https://tools.ietf.org/html/rfc5545#section-3.2.19

We were having issues with floating times without the timezome specified per event.

From what I can remember we (I) tested with:
1. icalendar online validator https://icalendar.org/validator.html
2. icalendar python package https://github.com/collective/icalendar
3. personal use on web and desktop calendaring apps

**Comment by garrying** [comment]
Wonder if the issue is `VALUE=DATE-TIME`. Reading the `Date-Time` spec: https://icalendar.org/iCalendar-RFC-5545/3-3-5-date-time.html the examples include `TZID`

**Comment by dcwalk** [comment]
Totally @garrying! :flushed: 
I've tested/validated and I can access this new ics on both desktop OS X and android phone, so I think we're good if someone else can confirm the commit I pushed.

Out of curiousity-- any reason we are limiting to 20 most recent events?

**Comment by benhylau** [comment]
Thanks @dcwalk I will confirm with my phone tonight

**Comment by benhylau** [comment]
Hmm... all the events are off by an hour. For example, planning meeting starts 7:30 pm instead of 6:30 when added to my Android Calendar.

**Comment by dcwalk** [comment]
That might have to do with how we declare the start of daylight/standard time?
https://github.com/tomeshnet/tomesh.net/pull/142/files#diff-f4cfa0dabac7fe3b1fd9cc6a5877a9a5L10
Urgh, I'm the worst at this

**Comment by garrying** [comment]
f334cc7 fixes the standard/daylight issue with [ownCloud's ics](https://github.com/owncloud/calendar/blob/master/timezones/AMERICA-TORONTO.ics) for reference.

Also, I finally got a hold of an Android device and was able to replicate the original, not opening, issue, and the daylight/standard issue.

**Comment by garrying** [comment]
Not sure why the 20 post limit, but the file size doubles without it. I think we should keep it in for now.

**Comment by benhylau** [comment]
Confirmed working. Also, downloading again updates the time of previously added events, and will not "double add". Ready to merge 👍

**Pull request merged**
