### PR TITLE
Remote Markdown Plugin: Relative support

### PR DESCRIPTION
**Pull request by garrying**
- Fixes an issue with relative links not resolving with remote markdown pages
- Adds checks and conversion for `raw.githubusercontent` paths to `github.com` path with `blob`

### CODE REVIEW

**Comment by benhylau** [comment]
I was thinking to [just link to the original raw content](https://github.com/tomeshnet/tomesh.net/blob/remote-markdown-patch/_plugins/remote_markdown.rb#L27) so we are not coupled with the GitHub sources of `.md`. Obviously I need a better regex matcher than `./`. @garrying @darkdrgn2k thoughts?

**Comment by garrying** [comment]
@benhylau It's a bit jarring to go from a styled page to the raw content (with missing numeration in order lists, etc.). Thinking that it's worth serving up the GitHub `blob` version for now and adjust/change when we come across a case that doesn't work. The regex in this PR is `](./` and I'm not sure if it's better 🤔

**Comment by dcwalk** [comment]
agree about it being jarring!

**Comment by benhylau** [comment]
I was thinking `)[./*.md]` might be a safer match? Also we should add a `Modified by garry` I'm the header and add some comment on the edited lines about what is going on.

**Comment by garrying** [comment]
Updated with that match—think it's safer. Also added comments.

**Review by benhylau — APPROVED** [review]

**Pull request merged**
